version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_api
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app # mount source code
      - /app/node_modules # keep container node_modules
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - '**/dist/'
            - '**/node_modules/'
            - '**/*.js.map'
            - '**/*.tsbuildinfo'
        - action: sync
          path: ./test
          target: /app/test
          ignore:
            - '**/dist/'
            - '**/node_modules/'
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile
        - action: sync
          path: ./.env
          target: /app/.env

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: natours
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

volumes:
  postgres_data:
